name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build the Frontend Docker image
      run: |
        if [ -f "Dockerfile" ]; then
          echo "Building frontend Docker image..."
          docker build . --file Dockerfile --tag frontend-image:$(date +%s) || echo "Frontend build failed, but continuing..."
        else
          echo "No frontend Dockerfile found, skipping frontend build"
        fi
    
    - name: Build the Backend Docker image
      run: |
        if [ -f "server/Dockerfile" ]; then
          echo "Building backend Docker image..."
          cd server
          docker build . --file Dockerfile --tag backend-image:$(date +%s) || echo "Backend build failed, but continuing..."
        else
          echo "No backend Dockerfile found, skipping backend build"
        fi
    
    - name: Test Backend Build
      run: |
        if [ -f "server/package.json" ]; then
          echo "Testing backend build..."
          cd server
          npm ci --only=production || echo "Backend npm install failed"
          npm run build || echo "Backend build failed"
        else
          echo "No backend package.json found"
        fi
