name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Frontend Docker image
      run: |
        if [ -f "Dockerfile" ]; then
          docker build . --file Dockerfile --tag frontend-image:$(date +%s)
        else
          echo "No frontend Dockerfile found, skipping frontend build"
        fi
    
    - name: Build the Backend Docker image
      run: |
        if [ -f "server/Dockerfile" ]; then
          docker build ./server --file server/Dockerfile --tag backend-image:$(date +%s)
        else
          echo "No backend Dockerfile found, skipping backend build"
        fi
